CONTRIBUTING.md

Added information about how to fix a for ENFILE: file table overflow error.

Added troubleshooting section

---

docs/templates.md

Adds descriptions and instructions about the templates so the reader can have a better picture of the available templates and make a more informed decision.

Improves in the templates documentation.

---

CONTRIBUTING.md

Spent the last few hours trying to get nativescript working with xcode 8, this is how I did it!

Adding how to get started with xcode 8 to docs

---

package.json
platform/nativescript/plugins/navigator-plugin.js
platform/nativescript/plugins/router-plugin.js
samples/app/app-with-router-pages.js

This adds the ability to change the page transition for the router #68

feat: Add router transitions 

---

platform/nativescript/runtime/index.js

https://ru.vuejs.org/v2/guide/unit-testing.html
```
it('correctly sets the message when created', () => {
const vm = new Vue(MyComponent).$mount()
expect(vm.message).toBe('bye!')
})
```

fix for use Unit Testing

---

platform/nativescript/renderer/ViewNode.js
samples/app/171.js

See https://github.com/nativescript-vue/nativescript-vue/issues/171

Issue #171 fix. Make short boolean props work

---

platform/nativescript/renderer/ViewNode.js
platform/nativescript/runtime/modules/transition.js

More robust checking of the boolean value

---

platform/nativescript/runtime/components/tab-view-item.js
platform/nativescript/runtime/components/tab-view.js
platform/nativescript/runtime/index.js
samples/app/app-with-all-components.js
samples/app/app-with-tab-view.js
samples/package.json

Add rest of the UI components to the app-with-all-components sample app

---

platform/nativescript/util/index.js
samples/app/app-with-pages.js

See https://github.com/nativescript-vue/nativescript-vue/issues/276

Fix action bar rendering - issue #276

---

index.d.ts

otherwise Typescrpit will complain in strict mode

provide explicit type to data

---

platform/nativescript/plugins/navigator-plugin.js
platform/nativescript/renderer/ViewNode.js
platform/nativescript/runtime/components/frame.js
platform/nativescript/runtime/components/page.js
platform/nativescript/runtime/modules/transition.js
platform/nativescript/util/hmr.js

See https://github.com/nativescript-vue/nativescript-vue/issues/388

Quick and dirty fix for the #388 HMR issue

---

platform/nativescript/runtime/components/frame.js

Honour the ID of the <Frame> components in the App

---

platform/nativescript/compiler/modules/router.js

fix(router module): check the el.parent has tag property on router

---

platform/nativescript/runtime/index.js
samples/app/595.js

Fix "TypeError: Cannot read property 'nativeView' of undefined" accessing this.$options

---

index.d.ts

- Add optional frame property
related issue https://github.com/nativescript-vue/nativescript-vue/issues/587

fix: add optional frame property

---

CONSOLE_LOG_OVERRIDE.md
README.md
package.json
platform/nativescript/framework.js

Add a note in the Readme on how to bring it back at the app level

fix: remove the console override

---

index.d.ts
platform/nativescript/plugins/navigator-plugin.js

feat: added     resolveOnNavigated option

---

platform/nativescript/util/index.js

on an already registered one would crash

fix: calling registerElement from webpack

---

CONTRIBUTING.md

Mainly the Node.js and NS versions

Update the CONTRIBUTING.md document to the versions used actually

---

package.json
platform/nativescript/hooks/before-checkForChanges.js
platform/nativescript/hooks/before-watch.js
platform/nativescript/plugins/modal-plugin.js
platform/nativescript/plugins/navigator-plugin.js
platform/nativescript/runtime/index.js
platform/nativescript/util/index.js
samples/app/240.js
samples/app/595.js
samples/app/app-with-list-view.js
samples/app/app-with-pages.js
samples/app/app-with-v-template-components.js
samples/package.json

- add `nativescript-toasty` for `nativescript-vue-devtools` dependencies
- add sample that `$navigateTo` passed props

test(samples): add sample $navigateTo with props

---

index.d.ts

Fix navigate back type

---

platform/nativescript/plugins/navigator-plugin.js

fix: add global navigation methods

---

CONTRIBUTING.md
package.json

Also remove samples command that is now useless.

Update contributing docs now that sample runner is gone

---

platform/nativescript/plugins/navigator-plugin.js

fix: child of NavigationEntry key generated in render (#813)

---

src/nativescript/elements.ts

I have tried this locally and it is working

feat: add registerElement RootLayout

---

src/renderer/nodeOps.ts

This change adds support for scoped styles

feat: add scoped styles support

---

src/renderer/modules/style.ts

feat: better style binding support

---

src/dom/index.ts

closes https://github.com/nativescript-vue/nativescript-vue/issues/1012

fix: `el.nativeView` reactivity oddities

---

src/runtimeHelpers.ts

fix: reference returned instance

---

src/nativescript/elements.ts
src/registry/index.ts

fix: include the tabview element
