nativescript-vue/nativescript-vue

platform/nativescript/runtime/index.js
Resolves #24
The `UIGestureGraphEdge Assertion failure ...` seems pretty mystical to me, but I think it was due to the fact that the native ios views in the app-component are created **before** `application.start()`.
Moving `mountComponent()`(where the elements are created) inside the `create()` callback of the `application.start()`  seems to resolve the issue.
=> Create/mount all native views after app.start

README.md, samples/app/app-with-list-view.js, samples/package.json
This PR adds an example to the repo on how to use NativeScript UI plugin in your Vue app. It shows how to add a gradient like this:
=> Example how you can use NativeScript UI plugins in Vue

README.md, docs/_toc.md, docs/articles.md, docs/contributing.md, docs/elements/components/button.md, docs/elements/components/label.md, docs/elements/components/text-field.md, docs/elements/layout/absolute-layout.md, docs/elements/layout/dock-layout.md, docs/elements/layout/grid-layout.md, docs/elements/layout/stack-layout.md, docs/elements/layout/wrap-layout.md, docs/installation-nativescript-vue.md, docs/quick-start.md, docs/templates.md, docs/using-nativescript-plugins.md, docs/using-vue-modules.md
- worked on "Installation" and "Quick Start" pages
- moved NS plugins usage from readme to a standalone page
- added "Templates" and "Articles" pages
=> improuve docs

CONTRIBUTING.md
The current 1.4.0-alpha.X version is not working with NS 3.x anymore, so the contributing doc should not mention that version.
=> Update NS version requirements in contributing doc

build/sample-runner.js
Change `tns run ...` to `tns debug ...` which allows developer to debug the sample app in the chrome devtools
=> Allow debugging the app in chrome devtools while testing.

README.md, build/config.js, package.json, platform/nativescript/element-registry.js, platform/nativescript/framework.js, platform/nativescript/plugins/router-plugin.js, platform/nativescript/renderer/ViewNode.js, platform/nativescript/runtime/components/frame.js, platform/nativescript/runtime/components/list-view.js, platform/nativescript/runtime/components/page.js, platform/nativescript/runtime/modules/events.js, platform/nativescript/runtime/modules/transition.js, platform/nativescript/runtime/node-ops.js, platform/nativescript/util/index.js
This PR handles fixes and enhancements to the Vue Router when used in {N}-Vue:
* Introduce NativeScriptHistory in the router plugin (a proxy to the Router's default AbstractHistory).
* Correctly handle back button in Android and iOS without recreating the whole previous Page.
* Add transition prop to Frame component - can be transition name or {N} transition object with name, duration and curve - you can use ios: and android: prefixes to specify platform.
* Possibility to specify the page transition on router.push/replace/go - with an {N} transition object after location, like this:
```javascript
this.$router.push(`/car-details-edit/${this.car.name}`, {
transition: "slideTop"
});
```
* Remove buble plugin as NativeScript uses quite new V8/JSC engines with good ES6+ support.
=> Frame and Router fixes for 4.1+

__tests__/renderer/ViewNode.test.js, platform/nativescript/renderer/ViewNode.js, platform/nativescript/runtime/node-ops.js, samples/app/220.js
=> Fix `keep-alive` components weird issue

index.d.ts
Typings should not declare a module wereas they are already in the concerned module
Also, reusing Vue way of doing typings, and separating constructor from body to have better overriding capabilities
---
```typescript
import Vue from 'nativescript-vue'
import { RadSideDrawer } from 'nativescript-ui-sidedrawer'
import { Component } from 'components/decorator'
@Component({})
class TestComponent extends Vue {
$refs: {
drawer: Vue<RadSideDrawer>
mainContent: Vue<StackLayout>
drawerContent: Vue<StackLayout>,
}
mounted() {
// `drawerView` will be of type RadSideDrawer
const drawerView = this.$refs.drawer.nativeView
}
}
```
You can augment the same way you are augmenting with Vue:
```typescript
import Vue from 'vue'
import { Bus } from 'store/bus'
import * as moment from 'moment'
import { …
```
=> fix(typings): were not implemented correctly

platform/nativescript/framework.js
Probably there is a more elegant issue, but I'm not a roll-up expert.
See #300.
=> Fix rollup problem not exporting Vue as the default element. So using NS-vue from TS is harder

platform/nativescript/element-registry.js
It's obvious, function [canBeLeftOpenTag](https://github.com/nativescript-vue/nativescript-vue/blob/master/platform/nativescript/util/index.js#L13) is always returning undefined,
because canBeLeftOpen is a typo mistake, should be canBeLeftOpenTag.
=> Fixed canBeLeftOpenTag typo mistake in defaultViewMeta.

platform/nativescript/runtime/components/list-view.js
By design the `ListView` from the `tns-core-modules` has a default `itemTemplate` (a basic Label that uses the toString() of the data item). In a NativeScript + Vue application if you do not declare an `<v-template`> you get an error.
This PR will allow you to declare a ListView without a declared `<v-template>`
=> feat(list-view): Add support for default ListView item template

build/build.js, package.json, platform/nativescript/hooks/before-checkForChanges.js, platform/nativescript/hooks/before-watch.js, postinstall.js, preuninstall.js
Currently it is not possible to use vue template without bundle option. So we need to show an error in case when the user executes some command without bundle option.
This PR adds 2 hooks - before-checkForChanges and before-watch. Thеsе hooks will be triggered automatically by {N} CLI when the command is executed.
=> feat: show error when --bundle option is not provided when executing some commands from {N} CLI

index.d.ts
Fix:  `property 'registerElement' does not exist on type 'NativeScriptVueConstructor'.`
Currently, the function type is defined but was not included in the constructor.
=> add registerElement to NativeScriptVueConstructor

index.d.ts
Updated type definitions for `ModalOptions` as `$showModal` can accept `props` same as `$navigateTo`.
=> Extend ModalOptions type definitions

platform/nativescript/hooks/before-checkForChanges.js
In case `--bundle` is not passed, the `before-checkForChanges` hook should stop the execution. However, in case `--bundle` is passed, it should allow the process to continue. Currently, even when `--bundle` is passed, the hook breaks the execution with error that you need to pass `--bundle`. The problem is that the hook checks the flag based on CLI's internal representation of the flag, but the internal structure has been changed since the PR that added this functionality has been added. Fix the hook to have correct check for bundle flag.
=> fix: check correctly for passed `--bundle` option

platform/nativescript/hooks/before-checkForChanges.js, platform/nativescript/hooks/before-watch.js, platform/nativescript/hooks/helpers.js
In NativeScript CLI 6.0.0 release the bundle workflow will be the only one available. Currently, the nativescript-vue has some hooks that verify bundle is passed. There's no need of them for 6.0.0 release.
Implement a check based on the CLI's version and skip the validation in case CLI is 6.x.x or newer.
=> fix: make hooks compatible with CLI's 6.0.0 changes

platform/nativescript/runtime/components/list-view.js, samples/app/464.js
Just a small patch to fix #464.
I changed the `items` prop's type to `Object` and instead added a validator function which ensures `items` is either an `Array` or an `ObservableArray`. I also adapted the `@itemTap` event emitter correspondingly.
**Edit:** I also added a sample for the issue
=> Fix ObservableArray items in ListView (Fixes #464)

platform/nativescript/runtime/index.js
Ensure `application` module is loaded before overriding `global.__onLiveSyncCore`.
Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/943.
=> fix: import `application` module

platform/nativescript/runtime/index.js
Ensure `frame` module is loaded before overriding `global.__onLiveSyncCore` for Android.
Fixes NativeScript/nativescript-dev-webpack#943 for Android.
=> fix: import `frame` module

platform/nativescript/runtime/components/frame.js
=> Allow developers set the default clearHistory and backstackVisible options when the page is mounted in a frame

platform/nativescript/runtime/components/frame.js
=> Fix accessing this.$refs.foo if component is declared with ref="foo"

platform/nativescript/util/index.js
Just a bit of clean up.
This function is no longer used after commit ba4e9949cdea00adc9f6fc56e22334d2a01e4285.
=> Clean unused function deepProxy.

platform/nativescript/runtime/components/list-view.js, platform/nativescript/util/index.js
Fixes #565.
The `<NativeListView>` was not setting the `itemTemplates` property correctly.
I am not sure why it was setting `_itemTemplatesInternal` instead of `itemTemplates` before, but now it works. According to my tests, the cell recycling works properly with multi-templates and the scroll is visibly smoother.
For comparison of a before/after, see the [updated playground app](https://play.nativescript.org/?template=play-vue&id=KhyRrD&v=9). The list on the right is patched with this fix.
=> Fix listview cell recycling

platform/nativescript/framework.js, platform/nativescript/util/index.js
Add option to suppress bunch of logs responsible for listing rendered elements. They are preventing developer to see actual Vue Warns in the templates.
This will tackle the problem mentioned in this issue https://github.com/nativescript-vue/nativescript-vue/issues/479
=> Suppress render logs

platform/nativescript/renderer/ViewNode.js
Fixes https://github.com/NativeScript/nativescript-ui-feedback/issues/1182
I know this fix is kind of `code smells` as the real reason why the `referenceNode` has not any `parentNode` is the real cause of the issue. But I wanted @rigor789 to look at and point me in the right direction.
=> Fix odd App crash while using v-if inside the RLV's template

samples/app/555.js
See #555 
Additionally to the sample, I will document using the NS `@loaded` event instead of the Vue `mounted` one.
=> Sample app for reproducing the #555 issue

__tests__/renderer/ViewNode.test.js, __tests__/renderer/utils.test.js, build/config.js, platform/nativescript/element-registry.js, platform/nativescript/framework.js, platform/nativescript/plugins/navigator-plugin.js, platform/nativescript/renderer/ViewNode.js, platform/nativescript/renderer/utils.js, platform/nativescript/runtime/components/android.js, platform/nativescript/runtime/components/frame.js, platform/nativescript/runtime/components/ios.js, platform/nativescript/runtime/components/list-view.js, platform/nativescript/runtime/index.js, samples/app/464.js, samples/app/522.js, samples/app/app-to-check-android-events.js, samples/app/app-with-all-components.js, samples/app/package.json, samples/package.json, samples/webpack.config.js
Fixes #575 and #579
I really don't know if this is a worthy change as it would imply use NS >= 6.2 in our apps.
Maybe NS-vue 2.5.x is the version for looking ahead to the future or maybe the 3.x version is better for that.
=> Use NS 6.2 scoped NPM packages

platform/nativescript/runtime/components/tab-strip-item.js
Updating to use the new Tabs and BottomNavigation components [recommended to use in place of TabView](https://www.nativescript.org/blog/tabs-and-bottomnavigation-nativescripts-two-new-components). However, I quickly noticed that the `@tap` binding isn't currently working on an individual `TabStripItem` while the `@tapItem` was working on the parent `TabStrip`.
I've changed the component to use a render function to bind both the event listeners and the attributes so that `@tap` now works on individual tab items.
=> fix(TabStripItem): bind attributes and listeners; support tap listener

platform/nativescript/plugins/modal-plugin.js, samples/app/modals-on-top-of-modals.js
This is a minor fix, per @rigor789's suggestion on https://github.com/nativescript-vue/nativescript-vue/issues/612. This works, however, it is not tested since there were not very clear testing guidelines. Also, it's not a very elegant solution. There may be times where you're not aware that an other modal is open, etc. and may not know if you need to pass `target`. In that case, it's safer to just pass it. Anyway, I'm happy to discuss this further. Thanks!
=> fix: add minor fix to allow target being passed to

index.d.ts
The current navigateBack types are wrong; navigateBack is falsely advertised to accept a lot of options that only make sense for forward navigation.
___
On a related note, I see the linting setup in the project is outdated. In particular, `index.d.ts` which this PR goes against is not linted:
```
"prettier": "prettier --write \"{{platform,__test__}/**/*.js,samples/app/*.js}\""
```
I could come up with a PR that updates the linting setup to lint all source files.
I could also come up with a more powerful eslint + eslint-plugin-prettier setup.
Let me know if you have any interest in that.
=> fix: fix navigateTo types

platform/nativescript/plugins/navigator-plugin.js, platform/nativescript/runtime/components/frame.js, platform/nativescript/runtime/components/page.js
It comes from using nextTick.
nextTick was used to be able to read __isNavigatedTo from the mounted event.
I removed the need for __isNavigatedTo thus removing the need for the nextTick.
=> fix(ios): fix white screen on start

index.d.ts
I just found out that there is an option to suppress render logs by diving into the source code.
Adding the type to the config would have made this much easier to find for everyone.
This PR adds `suppressRenderLogs` to the config of the `NativescriptVueConstructor` making this wonderful feature more visible.
=> TypeScript suppressRenderLogs

platform/nativescript/framework.js
After the update to NS7 getCssFileName is no longer available in the core module you either have to call it from via import { Application } from '@nativescript/core' then call Application.getCssFileName() or require('@nativescript/core/application').getCssFileName() or require('@nativescript/core').Application.getCssFileName();
This is causing issues with live sync.
=> fix: wrong import for getCssFileName

platform/nativescript/runtime/modules/events.js, samples/app/748.js
- updateListener need a createOnceHandler in vue, add it
- update capture console.log for more clarity
- Add a reproduction sample
- Keep in line with [weex](https://github.com/vuejs/vue/blob/dev/src/platforms/weex/runtime/modules/events.js)
Initial error 
```
An uncaught Exception occurred on "main" thread.
Unable to start activity ComponentInfo{org.nativescript.application/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: createOnceHandler is not a function
```
=> Fix once directive

platform/nativescript/element-registry.js
This PR adds `RootLayout` to Vue's element-registry. This is the changes required for `RootLayout` to work with Vue (https://github.com/NativeScript/NativeScript/pull/8980). This is dependent on Nativescript's `release/8.0.0` branch.
cc @NathanWalker
=> feat: add rootlayout to element-registry

CHANGELOG.md, package.json, packages/nativescript-vue-template-compiler/package.json, platform/nativescript/plugins/navigator-plugin.js, platform/nativescript/util/frame.js, samples/app/entry.js, samples/app/multiple-default-frames.js, samples/app_resources/Android/src/main/AndroidManifest.xml, samples/nativescript.config.ts, samples/package.json, samples/webpack.config.js
This handles a case where a frame with a different id might have overridden the previous frame with the same id, but has been unmounted.
/cc @farfromrefug
=> fix: fallback frame when navigating

index.d.ts
This changes allows all N-vue features like `$navigateTo` to be available through templates and default vue projects
=> fix: typings using augmentation

demo/app/components/FragmentRootComponent.vue, demo/app/components/GH1017.vue, src/index.ts
Fixes #1017
When importing a {N} view in `script setup` and using it with the same name in the template, Vue tries to resolve the {N} view as a component and it fails. With this change, we override the render helpers to hijack the first `type` argument, and detect when it's a `{N}` view (or a known component) and we return it's name instead, so the renderer can render it correctly.
=> fix: handle views imported in script setup

src/nativescript/elements.ts
The `ProxyViewContainer` element was not registered which broke apps that were migrated from NSVue2.
=> Register ProxyViewContainer

nativescript.webpack.js
This line makes it go through the vue and base configuration twice in ns/webpack
=> remove multiple calls to useConfig vue and base

src/plugins/navigation.ts
This PR is an attempt to fix #1091 while also making use of NativeScript's `disposeNativeView` event.
=> fix: page unmount type error

src/index.ts
Log an error with the actual problem. Changes the console output when an error occurs from this:
which doesn't give any information about what the error is
to this:
=> More useful error logging
